image: alpine/latest
packages:
  - bash
  - icu-libs
  - krb5-libs
  - libgcc
  - libintl
  - libssl1.1
  - libssl1.1
  - zlib
sources:
  - https://git.sr.ht/~ivar/IOL.VippsEcommerce
tasks:
  - install-dotnet: |
      wget https://dot.net/v1/dotnet-install.sh
      chmod +x dotnet-install.sh
      bash dotnet-install.sh -c 5.0
  - display-dotnet-info: |
      ./.dotnet/dotnet --info
  - restore: |
      ./.dotnet/dotnet restore src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
  - build: |
      ./.dotnet/dotnet build --no-restore src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
  - test: |
      ./.dotnet/dotnet test --no-build --verbosity normal src/IOL.VippsEcommerce.Tests/IOL.VippsEcommerce.Tests.csproj
